### ISSUE TITLE
Incorrect scaling of recipes with large serving size

### ISSUE THREAD

**Issue by stleusc** [phantomate/Untare#37]
### Bug Summary

Create a recipe and add 5 ingredients, 200g, 900g, 1100g, 600g, 2200g.
Change yield to 5000 (g).

### Reproduction Steps

Change servings from 5000 to 5001.

### Expected Results

Website correctly calculates 200.04, 900.18, 1100.22, 600.12, 2200.44
Expected the app to do the same.

You wonder why I picked 5000? I needed a way to make decimal servings. Meaning, I wanted yield to be 5kg. But then the app does not allow me to do 7.25kg. That would help the most!

Because now I would have to use + button 2250 times!
Servings number should be editable with click or something

### Actual Results

App calculates 202, 909, 1111, 606, 2222. 
Which is 1% more than the original recipe.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by stleusc** [comment]
https://github.com/phantomate/Untare/blob/e9209d1acfbd766d300f627686dfdddf525daaba/lib/components/widgets/recipe_detail_tabbar_widget.dart#L265C36-L265C36

**Comment by stleusc** [comment]
```java
    double rawAmount = (ingredient.amount * (((newServing/initServing))*100).ceil()/100);
```
The following happens (new=5001, init=5000, amount=5000)
1. newServing/initServing: 5001/5000=1.0002
2. *100: =100.02
3. ceil(): = 101
4. ingredient.amount *: 5000*101 = 505000
5. /100: = 505000/100 = 5050

It should be obvious that the CORRECT rawAmount should be 5001.

The mistake is on the precedence of .ceil()!

Correct way:
1. newServing/initServing: 5001/5000=1.0002
2. ingredient.amount *: 5000*100.02 = 500100
3. *100: =100.02
4. ceil(): = 500100
5. /100: = 500100/100 = 5001

```java
    double rawAmount = (((ingredient.amount * (newServing/initServing)) * 100).ceil() / 100);
```

Your goal is to limit to 2 decimals, right?
And logical order is to calculate the new amount first, [amount * (new/init)]
THEN you limit to 2 decimals, (using ceil for rounding) by *100, round, /100
My sample code should do exactly that.

**Comment by MeisterBob** [comment]
This also happens with small numbers. 1 pc per serving ends in 3, 4.02, 5.01, 6, ...  or 3, 4 1/50, 5 1/100, 6, ... pcs when you change servings. 1 per 3 servings ends up with 1 17/50, 1 67/100 for 4 and 5 servings instead of 1 1/3 and 1 2/3.

Actually there is no need for `ceil()`ing and */100, because `toFormattedString()` rounds to 2 decimal places and `toMixedFraction()` returns better results when the value is not prerounded.

`    double rawAmount = ingredient.amount * newServing / initServing;`
does is what I would do here. You don't have to be smarter than Dart.

**Comment by phantomate** [comment]
Corrected the calculation
